import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Eye, FileText, Search, X } from "lucide-react";

import DashboardLayout from "../../layouts/DashboardLayout";
import {
  downloadAdminReportPdf,
  getAdminReportDetail,
  getAdminReports,
} from "../../services/api";
import "../../styles/admin.css";


const roles = ["", "Athlete", "Coach", "Physiotherapist", "Sports Scientist", "Administrator"];
const pageSize = 25;


function formatDate(value) {
  if (!value) return "Not available";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return "Not available";
  return parsed.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}

function formatNumber(value) {
  return value === null || value === undefined ? "Not tracked" : new Intl.NumberFormat().format(Number(value) || 0);
}

function statusClass(status) {
  return String(status || "unavailable").toLowerCase().replace(/\s+/g, "-");
}

function DetailBlock({ label, value }) {
  if (value === undefined || value === null || value === "") return null;
  return (
    <div className="admin-detail-block">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

function AdminReportManagement() {
  const [filters, setFilters] = useState({
    search: "",
    report_type: "",
    sport: "",
    creator_role: "",
    date_from: "",
    date_to: "",
    report_status: "",
  });
  const [page, setPage] = useState(0);
  const [data, setData] = useState(null);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);
  const [downloadingId, setDownloadingId] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const loadReports = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const response = await getAdminReports({
        ...filters,
        limit: pageSize,
        offset: page * pageSize,
      });
      setData(response);
    } catch (error) {
      setError(error.message || "Failed to load reports.");
    } finally {
      setLoading(false);
    }
  }, [filters, page]);

  useEffect(() => {
    const timeout = setTimeout(loadReports, 250);
    return () => clearTimeout(timeout);
  }, [loadReports]);

  function updateFilter(event) {
    const { name, value } = event.target;
    setFilters((current) => ({ ...current, [name]: value }));
    setPage(0);
  }

  async function openReport(reportId) {
    setDetailLoading(true);
    setError("");
    try {
      const report = await getAdminReportDetail(reportId);
      setSelectedReport(report);
    } catch (error) {
      setError(error.message || "Failed to load report details.");
    } finally {
      setDetailLoading(false);
    }
  }

  async function handleDownload(report) {
    setDownloadingId(report.report_id);
    setError("");
    setSuccess("");
    try {
      await downloadAdminReportPdf(report.report_id);
      setSuccess("Report download started.");
    } catch (error) {
      setError(error.message || "Failed to download report.");
    } finally {
      setDownloadingId("");
    }
  }

  const reports = Array.isArray(data?.reports) ? data.reports : [];
  const total = Number(data?.total) || 0;
  const totalPages = Math.max(Math.ceil(total / pageSize), 1);
  const summary = data?.summary || {};
  const cards = useMemo(
    () => [
      { label: "Total Reports", value: summary.total_reports },
      { label: "Reports This Period", value: summary.reports_this_period },
      { label: "Pending / Processing", value: summary.pending_processing },
      { label: "Archived", value: summary.archived },
    ],
    [summary]
  );

  return (
    <DashboardLayout>
      <main className="admin-page">
        <section className="admin-page-header">
          <div>
            <p className="page-eyebrow">REPORT MANAGEMENT</p>
            <h1>Report Management</h1>
            <p>Manage and review reports generated by the platform.</p>
          </div>
        </section>

        <section className="admin-filter-card analytics-filter-card">
          <label className="admin-search-field">
            <Search size={17} />
            <input name="search" value={filters.search} onChange={updateFilter} placeholder="Search report name or creator" />
          </label>
          <label><span>Report Type</span><select name="report_type" value={filters.report_type} onChange={updateFilter}><option value="">All types</option>{(data?.report_types || []).map((item) => <option key={item} value={item}>{item}</option>)}</select></label>
          <label><span>Sport</span><select name="sport" value={filters.sport} onChange={updateFilter}><option value="">All sports</option>{(data?.sports || []).map((sport) => <option key={sport} value={sport}>{sport}</option>)}</select></label>
          <label><span>Creator / Role</span><select name="creator_role" value={filters.creator_role} onChange={updateFilter}>{roles.map((role) => <option key={role || "ALL"} value={role}>{role || "All roles"}</option>)}</select></label>
          <label><span>From</span><input name="date_from" type="date" value={filters.date_from} onChange={updateFilter} /></label>
          <label><span>To</span><input name="date_to" type="date" value={filters.date_to} onChange={updateFilter} /></label>
          <label><span>Status</span><select name="report_status" value={filters.report_status} onChange={updateFilter}><option value="">All statuses</option>{(data?.statuses || []).map((status) => <option key={status} value={status}>{status}</option>)}</select></label>
        </section>

        {success && <section className="admin-success-card">{success}</section>}
        {error && <section className="admin-error-card">{error}</section>}
        {detailLoading && <section className="admin-empty-card">Loading report details...</section>}
        {loading && <section className="admin-empty-card">Loading reports...</section>}

        {!loading && (
          <>
            <section className="admin-summary-grid">
              {cards.map((card) => (
                <article className="admin-summary-card" key={card.label}>
                  <div className="admin-icon-box"><FileText size={21} /></div>
                  <div><span>{card.label}</span><strong>{formatNumber(card.value)}</strong></div>
                </article>
              ))}
            </section>

            <section className="admin-panel-card">
              <div className="admin-panel-heading"><div><h2>Reports</h2><p>{total ? `${Math.min(page * pageSize + 1, total)}-${Math.min((page + 1) * pageSize, total)} of ${total}` : "No reports"}</p></div></div>
              {reports.length === 0 ? (
                <div className="admin-empty-state">No generated report records match the current filters.</div>
              ) : (
                <div className="admin-report-table">
                  <div className="admin-report-table-head"><span>Report</span><span>Type</span><span>Created By</span><span>Role</span><span>Sport</span><span>Created Date</span><span>Status</span><span>Actions</span></div>
                  {reports.map((report) => (
                    <article className="admin-report-table-row" key={report.report_id}>
                      <span>{report.report_name}</span>
                      <span>{report.report_type}</span>
                      <span>{report.created_by}</span>
                      <span>{report.creator_role}</span>
                      <span>{report.sport || "Not provided"}</span>
                      <span>{formatDate(report.created_date)}</span>
                      <span><span className={`admin-status-pill ${statusClass(report.status)}`}>{report.status}</span></span>
                      <span className="admin-report-actions">
                        <button className="admin-secondary-button" type="button" onClick={() => openReport(report.report_id)}><Eye size={15} />View</button>
                        <button className="admin-secondary-button" type="button" disabled={!report.pdf_available || downloadingId === report.report_id} onClick={() => handleDownload(report)}><Download size={15} />PDF</button>
                      </span>
                    </article>
                  ))}
                </div>
              )}
              <div className="admin-pagination">
                <button className="admin-secondary-button" type="button" disabled={page === 0} onClick={() => setPage((current) => Math.max(current - 1, 0))}>Previous</button>
                <span>Page {page + 1} of {totalPages}</span>
                <button className="admin-secondary-button" type="button" disabled={page + 1 >= totalPages} onClick={() => setPage((current) => current + 1)}>Next</button>
              </div>
            </section>
          </>
        )}

        {selectedReport && (
          <div className="admin-modal-backdrop">
            <section className="admin-modal">
              <div className="admin-modal-heading">
                <div><p className="page-eyebrow">REPORT DETAILS</p><h2>{selectedReport.report_name}</h2><span>{selectedReport.report_type}</span></div>
                <button className="admin-icon-button" type="button" aria-label="Close report details" onClick={() => setSelectedReport(null)}><X size={20} /></button>
              </div>
              <div className="admin-detail-grid">
                <DetailBlock label="Report Title" value={selectedReport.report_name} />
                <DetailBlock label="Report Type" value={selectedReport.report_type} />
                <DetailBlock label="Creator" value={selectedReport.created_by} />
                <DetailBlock label="Role" value={selectedReport.creator_role} />
                <DetailBlock label="Scope" value={selectedReport.scope} />
                <DetailBlock label="Sport" value={selectedReport.sport} />
                <DetailBlock label="Created Date" value={formatDate(selectedReport.created_date)} />
                <DetailBlock label="Status" value={selectedReport.status} />
              </div>
              <div className="admin-detail-section">
                <h3>Metadata</h3>
                <div className="admin-detail-grid">
                  {Object.entries(selectedReport.metadata || {}).map(([key, value]) => (
                    <DetailBlock key={key} label={key.replaceAll("_", " ")} value={value} />
                  ))}
                </div>
              </div>
              <div className="admin-modal-actions">
                <button className="admin-secondary-button" type="button" onClick={() => setSelectedReport(null)}>Close</button>
                <button className="admin-primary-button" type="button" disabled={!selectedReport.pdf_available || downloadingId === selectedReport.report_id} onClick={() => handleDownload(selectedReport)}><Download size={16} />Download PDF</button>
              </div>
              {!data?.archive_supported && <div className="admin-empty-state">Archive/unarchive is not supported by the existing report data model.</div>}
            </section>
          </div>
        )}
      </main>
    </DashboardLayout>
  );
}


export default AdminReportManagement;
